---
# tasks to grant svc-snowmqm user access to MQ
- name: Display queue manager on jgocsr000000153
  command: '{{ MQ.command_path }}/dspmq'
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "jgocsr000000153"

- name: setmqauth
  command: '{{ MQ.command_path }}/setmqaut -m BOCDR01 -t qmgr -g svc-snowmqm +connect +dsp +inq +crt'
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "jgocsr000000153"

- name: setmqauth
  command: "{{ MQ.command_path }}/setmqaut -m BOCDR01 -n '**' -t q -g svc-snowmqm +get +browse +put +dsp +inq "
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "jgocsr000000153"

- name: dspmqauth
  command: "{{ MQ.command_path }}/dspmqaut -m BOCDR01 -t qmgr -p svc-snowmqm"
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "jgocsr000000153"

#BNEDR01

- name: setmqauth
  command: '{{ MQ.command_path }}/setmqaut -m BNEDR01 -t qmgr -g svc-snowmqm +connect +dsp +inq +crt'
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "jgocsr000000153"

- name: setmqauth
  command: "{{ MQ.command_path }}/setmqaut -m BNEDR01 -n '**' -t q -g svc-snowmqm +get +browse +put +dsp +inq "
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "jgocsr000000153"

- name: dspmqauth
  command: "{{ MQ.command_path }}/dspmqaut -m BNEDR01 -t qmgr -p svc-snowmqm"
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "jgocsr000000153"

- name: Display queue manager on jgocsr000000154
  command: '{{ MQ.command_path }}/dspmq'
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "jgocsr000000154"

#PROD01 BOCPRD01

- name: Display queue manager on jgopsr000000254
  command: '{{ MQ.command_path }}/dspmq'
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "jgopsr000000254"

- name: setmqauth
  command: '{{ MQ.command_path }}/setmqaut -m BOCPRD01 -t qmgr -g svc-snowmqm +connect +dsp +inq +crt'
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "jgopsr000000254"

- name: setmqauth
  command: "{{ MQ.command_path }}/setmqaut -m BOCPRD01 -n '**' -t q -g svc-snowmqm +get +browse +put +dsp +inq "
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "jgopsr000000254"

- name: dspmqauth
  command: "{{ MQ.command_path }}/dspmqaut -m BOCPRD01 -t qmgr -p svc-snowmqm"
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "jgopsr000000254"

#PROD01 BNEPRD01

- name: setmqauth
  command: '{{ MQ.command_path }}/setmqaut -m BNEPRD01 -t qmgr -g svc-snowmqm +connect +dsp +inq +crt'
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "jgopsr000000254"

- name: setmqauth
  command: "{{ MQ.command_path }}/setmqaut -m BNEPRD01 -n '**' -t q -g svc-snowmqm +get +browse +put +dsp +inq "
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "jgopsr000000254"

- name: dspmqauth
  command: "{{ MQ.command_path }}/dspmqaut -m BNEPRD01 -t qmgr -p svc-snowmqm"
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "jgopsr000000254"

