#NBCICPPRDFLEX....................................................
- name: setmqauth NBCICPPRDFLEX
  command: '{{ MQ.command_path }}/setmqaut -m NBCICPPRDFLEX -t qmgr -g svc-snowmqm +connect +dsp +inq +crt'
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "tznbcrappmq01"

- name: setmqauth NBCICPPRDFLEX
  command: "{{ MQ.command_path }}/setmqaut -m NBCICPPRDFLEX -n '**' -t q -g svc-snowmqm +get +browse +put +dsp +inq "
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "tznbcrappmq01"

- name: dspmqauth NBCICPPRDFLEX
  command: "{{ MQ.command_path }}/dspmqaut -m NBCICPPRDFLEX -t qmgr -p svc-snowmqm"
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "tznbcrappmq01"

