---
# tasks to grant svc-snowmqm user access to MQ
- name: Display queue manager on MQLA00L1
  command: '{{ MQ.command_path }}/dspmq'
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "158.1.9.129"

#MQMBPROD01
- name: setmqauth MQLA00L1
  command: '{{ MQ.command_path }}/setmqaut -m MQLA00L1 -t qmgr -g svc-snowmqm +connect +dsp +inq +crt'
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "158.1.9.129"

- name: setmqauth MQLA00L1
  command: "{{ MQ.command_path }}/setmqaut -m MQLA00L1 -n '**' -t q -g svc-snowmqm +get +browse +put +dsp +inq "
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "158.1.9.129"

- name: dspmqauth MQLA00L1
  command: "{{ MQ.command_path }}/dspmqaut -m MQLA00L1 -t qmgr -p svc-snowmqm"
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "158.1.9.129"


