---
# tasks to grant svc-snowmqm user access to MQ
# BEMDR03
- name: setmqauth BEMDR03
  command: '{{ MQ.command_path }}/setmqaut -m BEMDR03 -t qmgr -g svc-snowmqm +connect +dsp +inq +crt'
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "jgocsr000000155.corp.dsarena.com"

- name: setmqauth BEMDR03
  command: "{{ MQ.command_path }}/setmqaut -m BEMDR03 -n '**' -t q -g svc-snowmqm +get +browse +put +dsp +inq "
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "jgocsr000000155.corp.dsarena.com"

- name: dspmqauth BEMDR03
  command: "{{ MQ.command_path }}/dspmqaut -m BEMDR03 -t qmgr -p svc-snowmqm"
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "jgocsr000000155.corp.dsarena.com"

#BEMDR04
- name: setmqauth BEMDR04
  command: '{{ MQ.command_path }}/setmqaut -m BEMDR04 -t qmgr -g svc-snowmqm +connect +dsp +inq +crt'
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "jgocsr000000156.corp.dsarena.com"

- name: setmqauth BEMDR04
  command: "{{ MQ.command_path }}/setmqaut -m BEMDR04 -n '**' -t q -g svc-snowmqm +get +browse +put +dsp +inq "
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "jgocsr000000156.corp.dsarena.com"

- name: dspmqauth BEMDR04
  command: "{{ MQ.command_path }}/dspmqaut -m BEMDR04 -t qmgr -p svc-snowmqm"
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "jgocsr000000156.corp.dsarena.com"


