---
# tasks to grant svc-snowmqm user access to MQ
- name: Display MQLQ37L0
  command: '{{ MQ.command_path }}/dspmq'
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "jhbpsr000000818"

#MQLQ37L0....................................................
- name: setmqauth MQLQ37L0
  command: '{{ MQ.command_path }}/setmqaut -m MQLQ37L0 -t qmgr -g svc-snowmqm +connect +dsp +inq +crt'
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "jhbpsr000000818"

- name: setmqauth MQLQ37L0
  command: "{{ MQ.command_path }}/setmqaut -m MQLQ37L0 -n '**' -t q -g svc-snowmqm +get +browse +put +dsp +inq "
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "jhbpsr000000818"

- name: dspmqauth MQLQ37L0
  command: "{{ MQ.command_path }}/dspmqaut -m MQLQ37L0 -t qmgr -p svc-snowmqm"
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "jhbpsr000000818"
  
