---
# tasks to grant svc-snowmqm user access to MQ
- name: Display queue manager on jgocsr000000153
  command: '{{ MQ.command_path }}/dspmq'
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "jgocsr000000153"

- name: setmqauth
  command: '{{ MQ.command_path }}/setmqaut -m BEMDR01 -t qmgr -g svc-snowmqm +connect +dsp +inq +crt'
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "jgocsr000000153"

- name: setmqauth
  command: "{{ MQ.command_path }}/setmqaut -m BEMDR01 -n '**' -t q -g svc-snowmqm +get +browse +put +dsp +inq "
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "jgocsr000000153"

- name: dspmqauth
  command: "{{ MQ.command_path }}/dspmqaut -m BEMDR01 -t qmgr -p svc-snowmqm"
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "jgocsr000000153"

- name: Display queue manager on jgocsr000000154
  command: '{{ MQ.command_path }}/dspmq'
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "jgocsr000000154"

- name: setmqauth
  command: '{{ MQ.command_path }}/setmqaut -m BEMDR02 -t qmgr -g svc-snowmqm +connect +dsp +inq +crt'
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "jgocsr000000154"

- name: setmqauth
  command: "{{ MQ.command_path }}/setmqaut -m BEMDR02 -n '**' -t q -g svc-snowmqm +get +browse +put +dsp +inq "
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "jgocsr000000154"

- name: dspmqauth
  command: "{{ MQ.command_path }}/dspmqaut -m BEMDR02 -t qmgr -p svc-snowmqm"
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "jgocsr000000154"

