---
# tasks to grant svc-snowmqm user access to MQ
- name: Display queue manager on ZAPRNBRAPP0039
  command: '{{ MQ.command_path }}/dspmq'
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "ZAPRNBRAPP0039"

# BEMDR03
- name: setmqauth MQMBPROD01 on ZAPRNBRAPP0039
  command: '{{ MQ.command_path }}/setmqaut -m MQMBPROD01 -t qmgr -g svc-snowmqm +connect +dsp +inq +crt'
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "ZAPRNBRAPP0039"

- name: setmqauth MQMBPROD01
  command: "{{ MQ.command_path }}/setmqaut -m MQMBPROD01 -n '**' -t q -g svc-snowmqm +get +browse +put +dsp +inq "
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "ZAPRNBRAPP0039"

- name: dspmqauth MQMBPROD01
  command: "{{ MQ.command_path }}/dspmqaut -m MQMBPROD01 -t qmgr -p svc-snowmqm"
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "ZAPRNBRAPP0039"

#BEMDR04
- name: setmqauth MQMBPROD02
  command: '{{ MQ.command_path }}/setmqaut -m MQMBPROD02 -t qmgr -g svc-snowmqm +connect +dsp +inq +crt'
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "ZAPRNBRAPP0040"

- name: setmqauth MQMBPROD02
  command: "{{ MQ.command_path }}/setmqaut -m MQMBPROD02 -n '**' -t q -g svc-snowmqm +get +browse +put +dsp +inq "
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "ZAPRNBRAPP0040"

- name: dspmqauth MQMBPROD02
  command: "{{ MQ.command_path }}/dspmqaut -m MQMBPROD01 -t qmgr -p svc-snowmqm"
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "ZAPRNBRAPP0040"



