---
# tasks to grant svc-snowmqm user access to MQ
- name: Display queue manager on EBOXPRD01AQMGR
  command: '{{ MQ.command_path }}/dspmq'
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "zapsdcrapp1132"

#EBOXPRD01AQMGR....................................................
- name: setmqauth EBOXPRD01AQMGR
  command: '{{ MQ.command_path }}/setmqaut -m EBOXPRD01AQMGR -t qmgr -g svc-snowmqm +connect +dsp +inq +crt'
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "zapsdcrapp1132"

- name: setmqauth EBOXPRD01AQMGR
  command: "{{ MQ.command_path }}/setmqaut -m EBOXPRD01AQMGR -n '**' -t q -g svc-snowmqm +get +browse +put +dsp +inq "
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "zapsdcrapp1132"

- name: dspmqauth EBOXPRD01AQMGR
  command: "{{ MQ.command_path }}/dspmqaut -m EBOXPRD01AQMGR -t qmgr -p svc-snowmqm"
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "zapsdcrapp1132"

#EBOXPRD02AQMGR.......................................................
#- name: setmqauth EBOXPRD02AQMGR
#  command: '{{ MQ.command_path }}/setmqaut -m EBOXPRD02AQMGR -t qmgr -g svc-snowmqm +connect +dsp +inq +crt'
#  become: yes
#  become_user: '{{ MQ.user }}'
#  when: ansible_hostname == "ZAPSDCRAPP1133"

    #- name: setmqauth EBOXPRD02AQMGR
    #  command: "{{ MQ.command_path }}/setmqaut -m EBOXPRD02AQMGR -n '**' -t q -g svc-snowmqm +get +browse +put +dsp +inq "
    #  become: yes
    #become_user: '{{ MQ.user }}'
    #when: ansible_hostname == "ZAPSDCRAPP1133"

    #- name: dspmqauth EBOXPRD02AQMGR
    #command: "{{ MQ.command_path }}/dspmqaut -m EBOXPRD02AQMGR -t qmgr -p svc-snowmqm"
    #become: yes
    #become_user: '{{ MQ.user }}'
    #when: ansible_hostname == "ZAPSDCRAPP1133"

#EBOXPRD03AQMGR.......................................................
- name: setmqauth EBOXPRD03AQMGR
  command: '{{ MQ.command_path }}/setmqaut -m EBOXPRD03AQMGR -t qmgr -g svc-snowmqm +connect +dsp +inq +crt'
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "ZAPRNBRAPP1110"

- name: setmqauth EBOXPRD03AQMGR
  command: "{{ MQ.command_path }}/setmqaut -m EBOXPRD03AQMGR -n '**' -t q -g svc-snowmqm +get +browse +put +dsp +inq "
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "ZAPRNBRAPP1110"

- name: dspmqauth EBOXPRD03AQMGR
  command: "{{ MQ.command_path }}/dspmqaut -m EBOXPRD03AQMGR -t qmgr -p svc-snowmqm"
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "ZAPRNBRAPP1110"

#EBOXPRD04AQMGR......................................................
- name: setmqauth EBOXPRD04AQMGR
  command: '{{ MQ.command_path }}/setmqaut -m EBOXPRD04AQMGR -t qmgr -g svc-snowmqm +connect +dsp +inq +crt'
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "ZAPRNBRAPP1111"

- name: setmqauth EBOXPRD04AQMGR
  command: "{{ MQ.command_path }}/setmqaut -m EBOXPRD04AQMGR -n '**' -t q -g svc-snowmqm +get +browse +put +dsp +inq "
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "ZAPRNBRAPP1111"

- name: dspmqauth EBOXPRD04AQMGR
  command: "{{ MQ.command_path }}/dspmqaut -m EBOXPRD04AQMGR -t qmgr -p svc-snowmqm"
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "ZAPRNBRAPP1111"


