---
# tasks to grant svc-snowmqm user access to MQ
- name: Display MQAPPLCLNP
  command: '{{ MQ.command_path }}/dspmq'
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "rmqfap.absa.co.za"

#SAAPRD01AQMGR....................................................
- name: setmqauth MQAPPLCLNP
  command: '{{ MQ.command_path }}/setmqaut -m MQAPPLCLNP -t qmgr -g svc-snowmqm +connect +dsp +inq +crt'
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "rmqfap.absa.co.za"

- name: setmqauth MQAPPLCLNP
  command: "{{ MQ.command_path }}/setmqaut -m MQAPPLCLNP -n '**' -t q -g svc-snowmqm +get +browse +put +dsp +inq "
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "rmqfap.absa.co.za"

- name: dspmqauth MQAPPLCLNP
  command: "{{ MQ.command_path }}/dspmqaut -m MQAPPLCLNP -t qmgr -p svc-snowmqm"
  become: yes
  become_user: '{{ MQ.user }}'
  when: ansible_hostname == "rmqfap.absa.co.za"
